import java.awt.image.BufferedImage;

public abstract class chooseCharacter {
    protected int hp;
    protected int maxhp;
    protected int y;
    protected int x = 50;
    protected int jumpHeight;
    protected int startAniY;
    protected BufferedImage[] startAni;
    protected BufferedImage[] stanceAni;
    protected BufferedImage[] moveR;
    protected BufferedImage[] moveL;
    protected BufferedImage[] jump;
    protected BufferedImage[] crouch;
    protected BufferedImage[] jumpr;
    protected BufferedImage[] jumpl;
    protected BufferedImage[] LP;
    protected BufferedImage[] MP;
    protected BufferedImage[] HP;
    protected BufferedImage[] LK;
    protected BufferedImage[] MK;
    protected BufferedImage[] HK;
    protected BufferedImage[] block;
    protected BufferedImage[] hitL;
    protected BufferedImage[] hitM;
    protected BufferedImage[] hitH;
    protected BufferedImage[] win1;
    protected BufferedImage[] win2;
    protected int AniWidth;
    protected int AniHeight;
    protected int startAniDelay;
    protected int stanceHeight;
    protected int stanceWidth;
    protected int defaultHeight;
    protected int defaultWidth;
    protected int moveWidth;
    protected int moveHeight;
    protected int crouchWidth;
    protected int crouchHeight;
    protected int jumpAniWidth;
    protected int jumpAniHeight;
    protected int jumpRWidth;
    protected int jumpRHeight;
    protected int jumpLWidth;
    protected int jumpLHeight;
    protected int LPdelay;
    protected int MPdelay;
    protected int HPdelay;
    protected int LKdelay;
    protected int MKdelay;
    protected int HKdelay;
    protected int hitdelay;
}