import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;

public class Ryu
extends chooseCharacter {
    private BufferedImage[] ryuStart = new BufferedImage[12];
    private BufferedImage[] ryuStance = new BufferedImage[5];
    private BufferedImage[] ryuMoveR = new BufferedImage[6];
    private BufferedImage[] ryuMoveL = new BufferedImage[6];
    private BufferedImage[] ryuJump = new BufferedImage[7];
    private BufferedImage[] ryuCrouch = new BufferedImage[2];
    private BufferedImage[] ryuJumpR = new BufferedImage[8];
    private BufferedImage[] ryuJumpL = new BufferedImage[8];
    private BufferedImage[] ryuLP = new BufferedImage[2];
    private BufferedImage[] ryuMP = new BufferedImage[3];
    private BufferedImage[] ryuHP = new BufferedImage[5];
    private BufferedImage[] ryuLK = new BufferedImage[5];
    private BufferedImage[] ryuMK = new BufferedImage[4];
    private BufferedImage[] ryuHK = new BufferedImage[6];
    private BufferedImage[] ryuBlock = new BufferedImage[2];
    private BufferedImage[] ryuHitL = new BufferedImage[2];
    private BufferedImage[] ryuWin1 = new BufferedImage[5];
    private BufferedImage[] ryuWin2 = new BufferedImage[6];

    void createImageArrays() throws IOException {
        BufferedImage ryuSpriteSheet = ImageIO.read(this.getClass().getClassLoader().getResource("Ryu.gif"));
        int width = 71;
        int height = 104;
        this.AniWidth = this.defaultWidth = width;
        this.moveWidth = this.defaultWidth;
        this.stanceWidth = this.defaultWidth;
        this.jumpRWidth = this.defaultWidth;
        this.jumpLWidth = this.defaultWidth;
        this.AniHeight = this.defaultHeight = height;
        this.moveHeight = this.defaultHeight;
        this.stanceHeight = this.defaultHeight;
        this.jumpRHeight = this.defaultHeight;
        this.jumpLHeight = this.defaultHeight;
        this.ryuStart[0] = ryuSpriteSheet.getSubimage(17, 107 - height, width, height);
        this.ryuStart[1] = ryuSpriteSheet.getSubimage(17, 107 - height, width, height);
        this.ryuStart[2] = ryuSpriteSheet.getSubimage(91, 107 - height, width, height);
        this.ryuStart[3] = ryuSpriteSheet.getSubimage(166, 107 - height, width, height);
        this.ryuStart[4] = ryuSpriteSheet.getSubimage(245, 107 - height, width, height);
        this.ryuStart[5] = ryuSpriteSheet.getSubimage(321, 107 - height, width, height);
        this.ryuStart[6] = ryuSpriteSheet.getSubimage(394, 107 - height, width, height);
        this.ryuStart[7] = ryuSpriteSheet.getSubimage(465, 107 - height, width, height);
        this.ryuStart[8] = ryuSpriteSheet.getSubimage(535, 108 - height, width, height);
        this.ryuStart[9] = ryuSpriteSheet.getSubimage(37, 221 - height, width, height);
        this.ryuStart[10] = ryuSpriteSheet.getSubimage(37, 221 - height, width, height);
        this.ryuStart[11] = ryuSpriteSheet.getSubimage(110, 221 - height, width, height);
        this.stanceHeight = 104;
        this.stanceWidth = 71;
        this.ryuStance[0] = ryuSpriteSheet.getSubimage(189, 221 - height, width, height);
        this.ryuStance[1] = ryuSpriteSheet.getSubimage(268, 221 - height, width, height);
        this.ryuStance[2] = ryuSpriteSheet.getSubimage(349, 221 - height, width, height);
        this.ryuStance[3] = ryuSpriteSheet.getSubimage(426, 221 - height, width, height);
        this.ryuStance[4] = ryuSpriteSheet.getSubimage(505, 221 - height, width, height);
        this.ryuMoveR[0] = ryuSpriteSheet.getSubimage(63, 331 - height, width, height);
        this.ryuMoveR[1] = ryuSpriteSheet.getSubimage(144, 331 - height, width, height);
        this.ryuMoveR[2] = ryuSpriteSheet.getSubimage(227, 331 - height, width, height);
        this.ryuMoveR[3] = ryuSpriteSheet.getSubimage(304, 331 - height, width, height);
        this.ryuMoveR[4] = ryuSpriteSheet.getSubimage(378, 331 - height, width, height);
        this.ryuMoveR[5] = ryuSpriteSheet.getSubimage(454, 331 - height, width, height);
        this.ryuMoveL[0] = ryuSpriteSheet.getSubimage(65, 441 - height, width, height);
        this.ryuMoveL[1] = ryuSpriteSheet.getSubimage(142, 441 - height, width, height);
        this.ryuMoveL[2] = ryuSpriteSheet.getSubimage(220, 441 - height, width, height);
        this.ryuMoveL[3] = ryuSpriteSheet.getSubimage(291, 441 - height, width, height);
        this.ryuMoveL[4] = ryuSpriteSheet.getSubimage(368, 441 - height, width, height);
        this.ryuMoveL[5] = ryuSpriteSheet.getSubimage(455, 441 - height, width, height);
        this.jumpAniHeight = 108;
        this.jumpAniWidth = 67;
        this.ryuJump[0] = ryuSpriteSheet.getSubimage(114, 568 - this.jumpAniHeight, this.jumpAniWidth, this.jumpAniHeight);
        this.ryuJump[1] = ryuSpriteSheet.getSubimage(192, 568 - this.jumpAniHeight, this.jumpAniWidth, this.jumpAniHeight);
        this.ryuJump[2] = ryuSpriteSheet.getSubimage(273, 568 - this.jumpAniHeight, this.jumpAniWidth, this.jumpAniHeight);
        this.ryuJump[3] = ryuSpriteSheet.getSubimage(273, 568 - this.jumpAniHeight, this.jumpAniWidth, this.jumpAniHeight);
        this.ryuJump[4] = ryuSpriteSheet.getSubimage(347, 568 - this.jumpAniHeight, this.jumpAniWidth, this.jumpAniHeight);
        this.ryuJump[5] = ryuSpriteSheet.getSubimage(424, 568 - this.jumpAniHeight, this.jumpAniWidth, this.jumpAniHeight);
        this.ryuJump[6] = ryuSpriteSheet.getSubimage(505, 568 - this.jumpAniHeight, this.jumpAniWidth, this.jumpAniHeight);
        this.crouchWidth = 73;
        this.crouchHeight = 64;
        this.ryuCrouch[0] = ryuSpriteSheet.getSubimage(8, 668 - this.crouchHeight, this.crouchWidth, this.crouchHeight);
        this.ryuCrouch[1] = ryuSpriteSheet.getSubimage(88, 668 - this.crouchHeight, this.crouchWidth, this.crouchHeight);
        this.ryuJumpR[0] = ryuSpriteSheet.getSubimage(177, 684 - height - 10, width, height + 10);
        this.ryuJumpR[1] = ryuSpriteSheet.getSubimage(254, 684 - height, width, height + 10);
        this.ryuJumpR[2] = ryuSpriteSheet.getSubimage(331, 684 - height, 93, height + 10);
        this.ryuJumpR[3] = ryuSpriteSheet.getSubimage(445, 684 - height, width, height + 10);
        this.ryuJumpR[4] = ryuSpriteSheet.getSubimage(517, 684 - height, 117, height + 10);
        this.ryuJumpR[5] = ryuSpriteSheet.getSubimage(11, 803 - height, width, height + 10);
        this.ryuJumpR[6] = ryuSpriteSheet.getSubimage(104, 803 - height, width, height + 10);
        this.ryuJumpR[7] = ryuSpriteSheet.getSubimage(184, 803 - height, width, height + 10);
        this.ryuJumpL[7] = ryuSpriteSheet.getSubimage(177, 684 - height - 10, width, height + 10);
        this.ryuJumpL[6] = ryuSpriteSheet.getSubimage(254, 684 - height, width, height + 10);
        this.ryuJumpL[5] = ryuSpriteSheet.getSubimage(331, 684 - height, 93, height + 10);
        this.ryuJumpL[4] = ryuSpriteSheet.getSubimage(445, 684 - height, width, height + 10);
        this.ryuJumpL[3] = ryuSpriteSheet.getSubimage(517, 684 - height, 117, height + 10);
        this.ryuJumpL[2] = ryuSpriteSheet.getSubimage(11, 803 - height, width, height + 10);
        this.ryuJumpL[1] = ryuSpriteSheet.getSubimage(104, 803 - height, width, height + 10);
        this.ryuJumpL[0] = ryuSpriteSheet.getSubimage(184, 803 - height, width, height + 10);
        this.ryuLP[0] = ryuSpriteSheet.getSubimage(433, 794 - height, width + 6, height);
        this.ryuLP[1] = ryuSpriteSheet.getSubimage(523, 794 - height, width + 36, height);
        this.LPdelay = 95;
        this.ryuMP[0] = ryuSpriteSheet.getSubimage(26, 917 - height, width, height);
        this.ryuMP[1] = ryuSpriteSheet.getSubimage(106, 917 - height, width, height);
        this.ryuMP[2] = ryuSpriteSheet.getSubimage(189, 916 - height, width + 39, height);
        this.MPdelay = 105;
        this.ryuHP[0] = ryuSpriteSheet.getSubimage(309, 915 - height, width + 10, height);
        this.ryuHP[1] = ryuSpriteSheet.getSubimage(403, 915 - height, width + 33, height);
        this.ryuHP[2] = ryuSpriteSheet.getSubimage(517, 915 - height, width + 7, height);
        this.ryuHP[3] = ryuSpriteSheet.getSubimage(4, 1031 - height, width + 7, height);
        this.ryuHP[4] = ryuSpriteSheet.getSubimage(96, 1031 - height, width, height);
        this.HPdelay = 110;
        this.ryuLK[0] = ryuSpriteSheet.getSubimage(176, 1031 - height, width + 15, height);
        this.ryuLK[1] = ryuSpriteSheet.getSubimage(270, 1031 - height, width, height);
        this.ryuLK[2] = ryuSpriteSheet.getSubimage(342, 1031 - height, width + 40, height);
        this.ryuLK[3] = ryuSpriteSheet.getSubimage(457, 1031 - height, width, height);
        this.ryuLK[4] = ryuSpriteSheet.getSubimage(536, 1031 - height, width + 15, height);
        this.LKdelay = 90;
        this.ryuMK[0] = ryuSpriteSheet.getSubimage(39, 1141 - height, 67, height);
        this.ryuMK[1] = ryuSpriteSheet.getSubimage(120, 1141 - height, 65, height);
        this.ryuMK[2] = ryuSpriteSheet.getSubimage(199, 1141 - height, 118, height);
        this.ryuMK[3] = ryuSpriteSheet.getSubimage(39, 1141 - height, 64, height);
        this.MKdelay = 110;
        this.ryuHK[0] = ryuSpriteSheet.getSubimage(328, 1142 - height, width, height);
        this.ryuHK[1] = ryuSpriteSheet.getSubimage(408, 1142 - height, width, height);
        this.ryuHK[2] = ryuSpriteSheet.getSubimage(484, 1142 - height, width + 16, height);
        this.ryuHK[3] = ryuSpriteSheet.getSubimage(5, 1257 - height, width + 40, height);
        this.ryuHK[4] = ryuSpriteSheet.getSubimage(124, 1257 - height, width + 20, height);
        this.ryuHK[5] = ryuSpriteSheet.getSubimage(232, 1257 - height, width, height);
        this.HKdelay = 100;
        this.ryuBlock[0] = ryuSpriteSheet.getSubimage(344, 794 - height, width, height);
        this.ryuBlock[1] = ryuSpriteSheet.getSubimage(258, 794 - height, width, height);
        this.ryuHitL[0] = ryuSpriteSheet.getSubimage(243, 2534, 77, 92);
        this.ryuHitL[1] = ryuSpriteSheet.getSubimage(333, 2533, 74, 91);
        this.hitdelay = 600;
        this.ryuWin1[0] = ryuSpriteSheet.getSubimage(437, 2764, 60, 92);
        this.ryuWin1[1] = ryuSpriteSheet.getSubimage(519, 2758, 62, 99);
        this.ryuWin1[2] = ryuSpriteSheet.getSubimage(3, 2861, 62, 119);
        this.ryuWin1[3] = ryuSpriteSheet.getSubimage(92, 2885, 67, 95);
        this.ryuWin1[4] = ryuSpriteSheet.getSubimage(178, 2886, 67, 94);
        this.ryuWin2[0] = ryuSpriteSheet.getSubimage(178, 2886, 67, 94);
        this.ryuWin2[1] = ryuSpriteSheet.getSubimage(260, 2885, 67, 94);
        this.ryuWin2[2] = ryuSpriteSheet.getSubimage(339, 2885, 67, 94);
        this.ryuWin2[3] = ryuSpriteSheet.getSubimage(418, 2885, 67, 94);
        this.ryuWin2[4] = ryuSpriteSheet.getSubimage(493, 2885, 67, 94);
        this.ryuWin2[5] = ryuSpriteSheet.getSubimage(567, 2885, 67, 94);
    }

    Ryu() throws IOException {
        this.createImageArrays();
        this.hp = 200;
        this.maxhp = 200;
        this.startAniY = 260;
        this.y = 260;
        this.jumpHeight = 50;
        this.startAniDelay = 100;
        this.startAni = this.ryuStart;
        this.stanceAni = this.ryuStance;
        this.moveR = this.ryuMoveR;
        this.moveL = this.ryuMoveL;
        this.jump = this.ryuJump;
        this.crouch = this.ryuCrouch;
        this.jumpr = this.ryuJumpR;
        this.jumpl = this.ryuJumpL;
        this.LP = this.ryuLP;
        this.MP = this.ryuMP;
        this.HP = this.ryuHP;
        this.LK = this.ryuLK;
        this.MK = this.ryuMK;
        this.HK = this.ryuHK;
        this.block = this.ryuBlock;
        this.hitL = this.ryuHitL;
        this.win1 = this.ryuWin1;
        this.win2 = this.ryuWin2;
    }
}